name: Test

on:
  push:

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actonlang/setup-acton@v1
#         with:
#           channel: 'tip'
#       - name: "Check out repository code"
#         uses: actions/checkout@v4
#       - run: acton build
#       - run: acton test
#       - run: acton test perf

  net-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actonlang/setup-acton@v1
        with:
          channel: 'tip'
      - name: "Check out repository code"
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: "Start quicklab"
        run: |
          make -C test/quicklab start
      - name: "Cache acton stuff"
        uses: actions/cache@v4
        with:
          # Is it safe to cache the out directory?
          path: |
            ~/.cache/acton
            out
          key: acton-${{ runner.os }}
      - run: acton build
      - run: acton test
