name: Test

on:
  push:

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actonlang/setup-acton@v1
#         with:
#           channel: 'tip'
#       - name: "Check out repository code"
#         uses: actions/checkout@v4
#       - run: acton build
#       - run: acton test
#       - run: acton test perf

  net-test:
    runs-on: ubuntu-latest
    env:
      IMAGE_PATH: ${{ vars.IMAGE_PATH }}
    steps:
      - name: Set up env for containers
        run: |
          # IOS XRd
          sudo sysctl -w fs.inotify.max_user_instances=64000
          # cRPD
          sudo apt install linux-modules-extra-$(uname -r) 
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          limit-access-to-actor: true
      - uses: actonlang/setup-acton@v1
        with:
          channel: 'tip'
      - name: "Check out repository code"
        uses: actions/checkout@v4
      - name: "Cache acton stuff"
        uses: actions/cache@v4
        with:
          # Is it safe to cache the out directory?
          path: |
            ~/.cache/acton
            out
          key: acton-${{ runner.os }}-${{ runner.arch }}
      - run: acton build
      - name: Login to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: "Start quicklab"
        run: |
          make -C test/quicklab start wait
      - name: "Configure quicklab"
        run: |
      - name: "Run quicklab tests"
        run: |
          timeout 120 bash -c 'until make -C test/quicklab test-ping; do echo "Retrying..."; sleep 2; done'
